# Generated by Django 5.0.4 on 2024-04-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('level', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'Skill',
                'ordering': ['id'],
            },
        ),
    ]
