# Generated by Django 5.0.4 on 2024-04-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_category_message_service_testimony_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
